[package]
name = "rustwalker"
version = "0.1.0"
edition = "2024"

[dependencies]
walkdir = "2.5"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
tempfile = "3.10"
chrono = "0.4" 